from nya_ml.models.sismetanin_rubert_toxic import SismetaninRuBertToxic
from nya_ml.models.blanchefort_rubert_sentiment import BlanchefortRuBertSentiment
from nya_ml.models.skolkovoInstitute_russian_toxicity_classifier import SkolkovoRuToxicityClassifier
from nya_ml.models.tatyana_rubert_sentiment import TatyanaRuBertSentiment
from nya_ml.models.constmodel import ConstRandModel
